"""Add universe clock settings

Revision ID: 63d657c89f24
Revises: 4bb4b8d65f67
Create Date: 2026-02-18 16:22:21.290850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d657c89f24'
down_revision: Union[str, Sequence[str], None] = '4bb4b8d65f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем, существует ли таблица universes и есть ли уже эти колонки
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Получаем список таблиц
    tables = inspector.get_table_names()
    
    # Если таблица universes существует, добавляем колонки
    if 'universes' in tables:
        columns = [col['name'] for col in inspector.get_columns('universes')]
        
        if 'clock_enabled' not in columns:
            op.add_column('universes', sa.Column('clock_enabled', sa.Integer(), nullable=True))
        if 'universe_start_year' not in columns:
            op.add_column('universes', sa.Column('universe_start_year', sa.Integer(), nullable=True))
        if 'universe_start_day' not in columns:
            op.add_column('universes', sa.Column('universe_start_day', sa.Integer(), nullable=True))
        if 'universe_start_hour' not in columns:
            op.add_column('universes', sa.Column('universe_start_hour', sa.Integer(), nullable=True))
        if 'universe_hours_per_day' not in columns:
            op.add_column('universes', sa.Column('universe_hours_per_day', sa.Integer(), nullable=True))
        if 'universe_days_per_year' not in columns:
            op.add_column('universes', sa.Column('universe_days_per_year', sa.Integer(), nullable=True))
        if 'universe_epoch_name' not in columns:
            op.add_column('universes', sa.Column('universe_epoch_name', sa.String(length=100), nullable=True))
        if 'universe_reference_real_date' not in columns:
            op.add_column('universes', sa.Column('universe_reference_real_date', sa.DateTime(), nullable=True))
        if 'universe_time_scale' not in columns:
            op.add_column('universes', sa.Column('universe_time_scale', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем, существует ли таблица universes
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    tables = inspector.get_table_names()
    
    if 'universes' in tables:
        columns = [col['name'] for col in inspector.get_columns('universes')]
        
        if 'universe_time_scale' in columns:
            op.drop_column('universes', 'universe_time_scale')
        if 'universe_reference_real_date' in columns:
            op.drop_column('universes', 'universe_reference_real_date')
        if 'universe_epoch_name' in columns:
            op.drop_column('universes', 'universe_epoch_name')
        if 'universe_days_per_year' in columns:
            op.drop_column('universes', 'universe_days_per_year')
        if 'universe_hours_per_day' in columns:
            op.drop_column('universes', 'universe_hours_per_day')
        if 'universe_start_hour' in columns:
            op.drop_column('universes', 'universe_start_hour')
        if 'universe_start_day' in columns:
            op.drop_column('universes', 'universe_start_day')
        if 'universe_start_year' in columns:
            op.drop_column('universes', 'universe_start_year')
        if 'clock_enabled' in columns:
            op.drop_column('universes', 'clock_enabled')
    # ### end Alembic commands ###
